export const GOALs = [
  {
    id: "1",
    goalTitle: "Increase Sales by 20%",
    goalType: "company",
    goalVisibility: "public",
    goalCycle: "Q1 2024",
    owners: ["Alice Johnson", "Bob Smith"],
    createdBy: "CEO",
    dueDate: "2024-03-31",
    currentProgressPercentage: 45,
  },
  {
    id: "2",
    goalTitle: "Improve Customer Satisfaction",
    goalType: "department",
    goalVisibility: "custom",
    goalCycle: "H1 2024",
    owners: ["Jane Doe"],
    createdBy: "Customer Service Manager",
    dueDate: "2024-06-30",
    currentProgressPercentage: 60,
  },
  {
    id: "3",
    goalTitle: "Launch New Marketing Campaign",
    goalType: "company",
    goalVisibility: "public",
    goalCycle: "Q2 2024",
    owners: ["Mark Lee", "Emily Davis"],
    createdBy: "Marketing Director",
    dueDate: "2024-06-15",
    currentProgressPercentage: 30,
  },
  {
    id: "4",
    goalTitle: "Enhance Product Quality",
    goalType: "department",
    goalVisibility: "private",
    goalCycle: "Q3 2024",
    owners: ["Lisa Green"],
    createdBy: "Product Manager",
    dueDate: "2024-09-30",
    currentProgressPercentage: 50,
  },
  {
    id: "5",
    goalTitle: "Reduce Operational Costs",
    goalType: "company",
    goalVisibility: "public",
    goalCycle: "FY 2024",
    owners: ["John Brown"],
    createdBy: "COO",
    dueDate: "2024-12-31",
    currentProgressPercentage: 20,
  },
  {
    id: "6",
    goalTitle: "Develop New Training Program",
    goalType: "individual",
    goalVisibility: "custom",
    goalCycle: "Q1 2024",
    owners: ["Sarah Miller"],
    createdBy: "HR Manager",
    dueDate: "2024-03-31",
    currentProgressPercentage: 70,
  },
  {
    id: "7",
    goalTitle: "Expand Market Reach",
    goalType: "company",
    goalVisibility: "public",
    goalCycle: "H2 2024",
    owners: ["Anna Wilson", "Tom Harris"],
    createdBy: "Sales Director",
    dueDate: "2024-12-15",
    currentProgressPercentage: 40,
  },
  {
    id: "8",
    goalTitle: "Update IT Infrastructure",
    goalType: "department",
    goalVisibility: "private",
    goalCycle: "FY 2024",
    owners: ["David Anderson"],
    createdBy: "IT Manager",
    dueDate: "2024-11-30",
    currentProgressPercentage: 55,
  },
  {
    id: "9",
    goalTitle: "Create New User Experience Design",
    goalType: "individual",
    goalVisibility: "custom",
    goalCycle: "Q2 2024",
    owners: ["Jessica White"],
    createdBy: "Design Lead",
    dueDate: "2024-06-30",
    currentProgressPercentage: 65,
  },
  {
    id: "10",
    goalTitle: "Increase Website Traffic",
    goalType: "company",
    goalVisibility: "public",
    goalCycle: "Q3 2024",
    owners: ["Kevin Adams"],
    createdBy: "Digital Marketing Manager",
    dueDate: "2024-09-30",
    currentProgressPercentage: 50,
  },
  {
    id: "11",
    goalTitle: "Optimize Supply Chain",
    goalType: "department",
    goalVisibility: "private",
    goalCycle: "FY 2024",
    owners: ["Rachel Moore"],
    createdBy: "Supply Chain Manager",
    dueDate: "2024-12-15",
    currentProgressPercentage: 25,
  },
  {
    id: "12",
    goalTitle: "Improve Employee Retention",
    goalType: "company",
    goalVisibility: "custom",
    goalCycle: "H1 2024",
    owners: ["Brian Clark"],
    createdBy: "HR Director",
    dueDate: "2024-06-30",
    currentProgressPercentage: 60,
  },
  {
    id: "13",
    goalTitle: "Implement New CRM System",
    goalType: "department",
    goalVisibility: "private",
    goalCycle: "Q4 2024",
    owners: ["Alice Johnson"],
    createdBy: "CRM Specialist",
    dueDate: "2024-12-31",
    currentProgressPercentage: 45,
  },
  {
    id: "14",
    goalTitle: "Develop New Product Line",
    goalType: "company",
    goalVisibility: "public",
    goalCycle: "FY 2024",
    owners: ["Mike Johnson", "Laura Scott"],
    createdBy: "Product Development Manager",
    dueDate: "2024-12-15",
    currentProgressPercentage: 35,
  },
  {
    id: "15",
    goalTitle: "Enhance Customer Support System",
    goalType: "department",
    goalVisibility: "custom",
    goalCycle: "H2 2024",
    owners: ["Emily Davis"],
    createdBy: "Customer Support Lead",
    dueDate: "2024-11-30",
    currentProgressPercentage: 75,
  },
];
